name: Deploy to Testnet

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/**/*.sol'
      - 'scripts/**/*.ts'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'contracts/**/*.sol'
      - 'scripts/**/*.ts'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy to Testnet
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          npx hardhat run scripts/deploy.ts --network goerli
          
      - name: Verify Contract
        env:
          DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
          CONFLUXSCAN_API_KEY: ${{ secrets.CONFLUXSCAN_API_KEY }}
        run: |
          npx hardhat verify --network confluxESpaceTestnet ${{ steps.deploy.outputs.contractAddress }} 