name: Generate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/**/*.sol'
      - 'docs/**/*.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'contracts/**/*.sol'
      - 'docs/**/*.md'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Documentation
        run: |
          npx hardhat docgen
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 