name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/**/*.sol'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'contracts/**/*.sol'
      - 'package.json'
      - 'package-lock.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Solhint
        run: |
          npx solhint 'contracts/**/*.sol'
          
      - name: Run Prettier
        run: |
          npx prettier --check 'contracts/**/*.sol' 