name: Mythril Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mythril:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mythril solc-select
          
      - name: Install and configure solc
        run: |
          solc-select install 0.8.28
          solc-select use 0.8.28
          
      - name: Run Mythril
        run: |
          echo "# Mythril Analysis Results" > mythril-report.md
          echo "" >> mythril-report.md
          for contract in contracts/*.sol; do
            echo "## Analyzing $contract" >> mythril-report.md
            echo "" >> mythril-report.md
            myth analyze "$contract" --max-depth 10 --execution-timeout 60 >> mythril-report.md 2>&1 || true
            echo "" >> mythril-report.md
          done
          
      - name: Upload Mythril Report
        uses: actions/upload-artifact@v4
        with:
          name: mythril-report
          path: mythril-report.md
          
      - name: Display Report
        run: |
          echo "Mythril Analysis Results:"
          cat mythril-report.md 