name: Slither Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer solc-select
          
      - name: Install and configure solc
        run: |
          solc-select install 0.8.28
          solc-select use 0.8.28
          
      - name: Run Slither
        run: |
          echo "# Slither Analysis Results" > slither-report.md
          echo "" >> slither-report.md
          for contract in contracts/*.sol; do
            echo "## Analyzing $contract" >> slither-report.md
            echo "" >> slither-report.md
            slither "$contract" >> slither-report.md 2>&1 || true
            echo "" >> slither-report.md
          done
          
      - name: Upload Slither Report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-report.md
          
      - name: Display Report
        run: |
          echo "Slither Analysis Results:"
          cat slither-report.md 