name: Solidity Version Compatibility

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/**/*.sol'
  pull_request:
    branches: [ main ]
    paths:
      - 'contracts/**/*.sol'

jobs:
  compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solc-version: ['0.8.0', '0.8.1', '0.8.2', '0.8.3', '0.8.4', '0.8.5', '0.8.6', '0.8.7', '0.8.8', '0.8.9', '0.8.10', '0.8.11', '0.8.12', '0.8.13', '0.8.14', '0.8.15', '0.8.16', '0.8.17', '0.8.18', '0.8.19', '0.8.20', '0.8.21', '0.8.22', '0.8.23', '0.8.24', '0.8.25', '0.8.26', '0.8.27', '0.8.28']
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install specific Solidity version
        run: |
          npm install solc@${{ matrix.solc-version }}
          
      - name: Compile contracts
        run: |
          npx hardhat compile
          
      - name: Run tests
        run: |
          npx hardhat test
          
      - name: Upload compilation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ matrix.solc-version }}
          path: |
            artifacts/
            cache/ 